// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tmunhucnfipvnkfwfhws.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRtdW5odWNuZmlwdm5rZndmaHdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NzU3ODgsImV4cCI6MjA3MDA1MTc4OH0.2fazA8xTz-Yfe7MT0Me1wt73TL_9cbjilcArrY0KNos";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});